apiVersion: apps/v1
kind: Deployment
metadata:
  name: employe-back
spec:
  selector:
    matchLabels:
      app: employe-back
  replicas: 3
  template:
    metadata:
      labels:
        app: employe-back
    spec:
      containers:
        - name: employe-back
          image: employe_back:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: employeemanager
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: MySQL123!!
---
apiVersion: v1
kind: Service
metadata:
  name: employe-back-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort:   # Port exposed to the outside
  selector:
    app: employe-back
  type: NodePort
